version: '3'
services:
  rso-storage:
    container_name: rso-storage
    image: storage:latest
    ports:
      - "8083:8083"
    environment:
      - KUMULUZEE_SERVER_BASEURL=http://${DOCKER_HOST_IP}:8083