apiVersion: v1
kind: Service
metadata:
  labels:
    app: storage
  name: storage
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    app: storage