apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage
  labels:
    app: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: storage-key
      containers:
        - image: kozeljko/storage
          name: storage
          ports:
            - containerPort: 8083
              name: storage
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json